name: Build

on:
  push:
    branches: [main]
  pull_request:
    types: [ opened, edited, reopened, review_requested ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Actions
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Run tests
        run: |
          deno test -A --unstable --coverage=./cov

      - name: Generate .lcov file
        run: deno coverage --unstable --lcov ./cov > cov.lcov

      - name: Upload coverage report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.codecov_token }}
          path-to-lcov: ./cov.lcov
