name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup Actions
        uses: actions/checkout@v2
      - name: setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: run tests
        run: |
          deno test -A
          